### PR TITLE
Added Docker support.

### PR DESCRIPTION
**Pull request by mrrooijen**
First of all, thanks for this awesome utility!

I've Dockerized it to make it more distributable, and so that the end-user doesn't have to install Ruby and its dependencies to use it.

Assuming you have Docker installed, you can simply run it like so:

``` bash
$ docker run \
  -e DNSIMPLE_API_USER=you@foo.org \
  -e DNSIMPLE_API_TOKEN=... \
  -e NAMES=foo.org,www/foo.org \
  -e ACME_CONTACT=mailto:you@foo.org \
  -v $(pwd)/live:/app/live \
  -ti meskyanichi/letsencrypt-dnsimple
```

Feel free to pull this in if you like. If you do, you probably want to setup automated builds against this repository on hub.docker.com so that the image automatically rebuilds on each git push. Then you can change `meskyanichi/letsencrypt-dnsimple` to `dpiddy/letsencrypt-dnsimple` in the README.

See commit messages for other small changes.

### CODE REVIEW

**Comment by danp** [comment]
Hi, sorry I missed this! I don't use docker much myself but would be happy to merge if you want to reopen.

**Comment by mrrooijen** [comment]
No worries!

I ended up creating a separate repository dedicated to Dockerizing your repository, and it doesn't require any code changes in your repository.

https://github.com/meskyanichi/dockerized-letsencrypt-dnsimple

Anyone that has Docker installed can run your script using the following command:

``` sh
$ docker run --rm \
  -e DNSIMPLE_API_USER=me@example.com \
  -e DNSIMPLE_API_TOKEN=... \
  -e NAMES=example.com,www/example.com \
  -e ACME_CONTACT=mailto:me@example.com \
  -v $(pwd)/live:/src/live \
  -ti meskyanichi/letsencrypt-dnsimple
```

The resulting certificate files will be placed in the (newly created) `./live` subfolder of the current working directory (that's the only difference between running the plain Ruby version and the Dockerized version due to how Docker mounts file system volumes).

Feel free to add the above command to your `README.md` if you want to provide it as an alternative option for non-Ruby users. :+1:

**Comment by danp** [comment]
Nice!

I just made the update in https://github.com/dpiddy/letsencrypt-dnsimple/commit/278641652a56780ab93189a41da40bb71d47e830.

**Comment by mrrooijen** [comment]
Sweet. Thanks again for the great utility!

**Pull request closed without merging**
